//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RelationsClient.ServiceReference1 {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="ServiceReference1.IDatabaseConnector")]
    public interface IDatabaseConnector {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IDatabaseConnector/hi", ReplyAction="http://tempuri.org/IDatabaseConnector/hiResponse")]
        string hi(string name);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IDatabaseConnector/hi", ReplyAction="http://tempuri.org/IDatabaseConnector/hiResponse")]
        System.Threading.Tasks.Task<string> hiAsync(string name);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IDatabaseConnectorChannel : RelationsClient.ServiceReference1.IDatabaseConnector, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class DatabaseConnectorClient : System.ServiceModel.ClientBase<RelationsClient.ServiceReference1.IDatabaseConnector>, RelationsClient.ServiceReference1.IDatabaseConnector {
        
        public DatabaseConnectorClient() {
        }
        
        public DatabaseConnectorClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public DatabaseConnectorClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public DatabaseConnectorClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public DatabaseConnectorClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public string hi(string name) {
            return base.Channel.hi(name);
        }
        
        public System.Threading.Tasks.Task<string> hiAsync(string name) {
            return base.Channel.hiAsync(name);
        }
    }
}
